// Automatically generated by scripts/fetch-editors.mjs
// Do not edit this file directly.

import log from '../log';
export interface IFoundEditor<T> {
  readonly editor: T
  readonly path: string
  readonly usesShell?: boolean
}
