// automatically generated by scripts/fetch-editors.mjs
// do not edit this file directly.

import log from '../log';
import { ExternalEditorError } from './shared'
import { IFoundEditor } from './found-editor'
import { getAvailableEditors as getAvailableEditorsDarwin } from './darwin'
import { getAvailableEditors as getAvailableEditorsWindows } from './win32'
import { getAvailableEditors as getAvailableEditorsLinux } from './linux'

let editorCache: ReadonlyArray<IFoundEditor<string>> | null = null

/**
 * Resolve a list of installed editors on the user's machine, using the known
 * install identifiers that each OS supports.
 */
export async function getAvailableEditors(): Promise<
  ReadonlyArray<IFoundEditor<string>>
> {
  if (!editorCache || editorCache.length === 0) {
    if (process.platform === 'darwin') {
      editorCache = await getAvailableEditorsDarwin()
    } else if (process.platform === 'win32') {
      editorCache = await getAvailableEditorsWindows()
    } else if (process.platform === 'linux') {
      editorCache = await getAvailableEditorsLinux()
    } else {
      log.warn(
        `Platform not currently supported for resolving editors: ${process.platform}`
      )
      return []
    }
  }

  return editorCache.toSorted((a, b) => a.editor.localeCompare(b.editor))
}

/**
 * Find an editor installed on the machine using the friendly name, or the
 * first valid editor if `null` is provided.
 *
 * Will throw an error if no editors are found, or if the editor name cannot
 * be found (i.e. it has been removed).
 */
export async function findEditorOrDefault(
  name: string | null
): Promise<IFoundEditor<string> | null> {
  const editors = await getAvailableEditors()
  if (editors.length === 0) {
    return null
  }

  if (name) {
    const match = editors.find(p => p.editor === name) || null
    if (!match) {
      const menuItemName = process.platform === 'darwin' ? 'Preferences' : 'Options'
      const message = `The editor '${name}' could not be found. Please open ${menuItemName} and choose an available editor.`

      throw new ExternalEditorError(message, { openPreferences: true })
    }

    return match
  }

  return editors[0]
}
